# Generated by Django 3.1.1 on 2020-10-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20200923_1225'),
        ('questions', '0002_question_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='queries',
            field=models.ManyToManyField(to='queries.Query'),
        ),
    ]
